### ISSUE TITLE
More visualization tools for device, circuit, and result.

### ISSUE THREAD

**Issue by junliangtan1** [qBraid/qBraid#214]
### What should we have?

we can extend the idea from #58, #213, adding more visualization tool option.

### Implementation

will need sometime explore all related visualization tools, and make a todo list for that.

**Comment by ryanhill1** [comment]
OpenQASM 3 [`drawer_circuit()`](https://github.com/qBraid/qBraid/blob/7bb7c8b7436741a0c26c3f5d61a4af9ccaa16a5a/qbraid/interface/qbraid_qasm/circuit_drawer.py#L330) function implemented with #247.

Still needs improvements: #269, #270 and to be integrated into top-level [`circuit_drawer()`](https://github.com/qBraid/qBraid/blob/7bb7c8b7436741a0c26c3f5d61a4af9ccaa16a5a/qbraid/interface/draw.py#L23) function.
