### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by junliangtan1** [qBraid/qBraid#220]
### What should we have?

we should have clear documentation for some of the function/class, like
- [ ] code documentaiton
- https://github.com/qBraid/qBraid/blob/aaa5239c5b3b533be42aa2ceb55bf220713e25a6/qbraid/interface/draw.py#L23-L31
- https://github.com/qBraid/qBraid/blob/aaa5239c5b3b533be42aa2ceb55bf220713e25a6/qbraid/interface/qbraid_braket/tools.py#L44-L46
- etc...

- [ ] better example for documentation, for example:
- full implementation of how to access different devices, plot method

### Implementation

explore each function, and improve the documentation.

**Comment by nitin-pandita** [comment]
I would love to contribute to this issue. Thanks

**Comment by ryanhill1** [comment]
@nitin-pandita Cool let me know if you have questions about this! See `CONTRIBUTING.md` documentation overview: https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#documentation

**Comment by nitin-pandita** [comment]
> @nitin-pandita Cool let me know if you have questions about this! See `CONTRIBUTING.md` documentation overview: https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#documentation

Sure thanks
