### ISSUE TITLE
qbraid token calculator

### ISSUE THREAD

**Issue by junliangtan1** [qBraid/qBraid#222]
### What should we have?

A calculator for how much qbraid token estimate spending, we can apply it on top of the device wrapper or calculate with input variable(shots) according to the device.

related to #32 and #33

**Comment by ryanhill1** [comment]
Should be an abstract method `estimate_run_cost` or similar implemented in the respective `QuantumDevice` class which returns USD estimate of quantum job.

For Amazon Braket, can potentially do programmatically via https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/tracking/pricing.py

TBD for IBM once pricing rolls out
