### ISSUE TITLE
OpenQASM 3.0 circuit drawer

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#227]
We would like to make our own stand-alone class/function(s) that allows circuit visualizations of OpenQASM files / strings. This class/function could leverage other visualization tools (e.g. Pylatex), but ideally would not have explicit dependency on any other quantum circuit packages. What we do *not* want, is a function that simply converts the openqasm code to a cirq, qiskit, or other circuit type, and then renders the circuit drawing from that package. Instead, we are looking for original code that parses a OpenQASM string (or file), and creates a circuit visualization / drawing (latex, plain text, or other) based on the qasm gates and operators pulled directly from the source code.

References:
- https://www.media.mit.edu/quanta/qasm2circ/
- https://arxiv.org/abs/2104.14722
- https://github.com/openqasm/openqasm
- https://openqasm.com/

Because of the large number of gates and operations supported by OpenQASM 3.0, we will restrict this first implementation to a smaller gate-set to make it a little more approachable. For this, you can use the following code to generate random qasm3 strings to use as the test data/files for the circuit drawer. Once the circuit drawer is reliably working for any circuits generated by this function, then we will consider this issue closed, and open a new issue that expands the scope.

```python
"""
Script to generate random OpenQASM 3.0 programs from restricted gate set

"""

import random
import numpy as np
from braket.circuits import Circuit, Instruction
from braket.circuits.gates import I, X, Y, Z, H, S, Si, V, Vi, Rx, Ry, Rz, GPi, GPi2
from braket.circuits.serialization import IRType


def random_circuit(num_qubits: int, num_instructions: int) -> Circuit:
    gate_set = [I(), X(), Y(), Z(), H(), S(), Si(), V(), Vi()]
    gate_set += [Rx(0.5), Ry(0.5), Rz(0.5), GPi(0.5), GPi2(0.5)]

    circ = Circuit()
    for _ in range(num_instructions):
        q = random.choice(range(num_qubits))
        gate = random.choice(gate_set)
        circ.add(Instruction(gate, [q]))
    return circ


n_qubits = np.random.randint(1, 6)
n_instrs = np.random.randint(3, 11)
circuit = random_circuit(n_qubits, n_instrs)
qasm3_str = circuit.to_ir(IRType.OPENQASM).source

with open("test.qasm", "w") as file:
    file.write(qasm3_str)

print(qasm3_str)
```

**Comment by Miguelillnino** [comment]
Hi! The issue seems interesting. Could I collaborate on this issue?

**Comment by ryanhill1** [comment]
@Miguelillnino Absolutely! Let me know if you have any questions :)

**Comment by CalebMcIrvinGitHub** [comment]
Hey, I'm new to open-source contributing, but I've also written code that works well on the sample input generator; how would I go about sharing my code? Would I create a new branch and link it to the issue?

**Comment by ryanhill1** [comment]
Hi @CalebMcIrvinGitHub, yes, you can also work on the issue! Per the [unitaryHack rules](https://unitaryhack.dev/rules/):

> For pull requests resolving bountied issues, the first **accepted** PR from the project maintainers will receive the prize!

To submit your code:
- Fork the repository
- Create a new branch and push your code
- Submit a pull request linking this issue

The rules don't say anything about collaborating with other contributors, but if both parties want to work together and potentially split the prize, I don't see a problem!

**Comment by Newtech66** [comment]
Do we need to support more than just ASCII output? For example, Latex output?

**Comment by ryanhill1** [comment]
Hi @Newtech66, for now just the ASCII output is sufficient. But if you would like to go beyond that, more power to you!

And an implementation that covers all the random_circuit possibilities is good. The Amazon Braket example above is somewhat restrictive, so using qiskit for these tests would probably be the best approach, e.g.:

```python
from qiskit.circuit.random import random_circuit
from qiskit.qasm3 import dumps

num_qubits = np.random.randint(1, 6)
depth = np.random.randint(1, 6)
circuit = random_circuit(num_qubits=n_qubits, depth=depth)
qasm3_str = dumps(circuit)
# test circuit drawer
...
```
