### ISSUE TITLE
Re-write `ResultWrapper.plot_counts` without qiskit

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#232]
Our [`qbraid.devices.ResultWrapper.plot_counts`](https://github.com/qBraid/qBraid/blob/581f3d7801040b5979c095aa0b83a15794c3f842/qbraid/devices/result.py#L66) method is used to create a display a histogram plot of the measurement counts from a job.

Currently, this method simply extends the functionality of the [`qiskit.visualization.plot_histogram()`](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_histogram.html) function. For now, this has worked ok. But going forward, we would like to write our own version of the plot histogram/ plot counts function so that we can give users more control over the axis labeling, graph title, qubit indexing, style, and other factors without dependence on qiskit.

You can use the qiskit function linked above as inspiration, ideally, we would like to create our own original version. If you do use code from qiskit, make sure to cite everything accordingly. The example on the Amazon Braket documentation page may also be helpful as a starting point: https://docs.aws.amazon.com/braket/latest/developerguide/braket-submit-tasks-to-braket.html#braket-example-results

**Comment by ryanhill1** [comment]
@nitin-pandita Great! Let me know if you have any questions :)

**Comment by ryanhill1** [comment]
@nitin-pandita Would you still like to work on this?

**Comment by nitin-pandita** [comment]
> @nitin-pandita Would you still like to work on this?

Sorry for the delay @ryanhill1 i am still working on it
