### ISSUE TITLE
Braket circuit compilation method for `AwsDeviceWrapper.run`

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#233]
## Unitary Hack scope

Transpile an Amazon Braket circuit to a circuit composed of native gates for IonQ Harmony device.

Implement function similar to [qiskit circuit transpiler](https://qiskit.org/documentation/apidoc/transpiler.html) for `braket.circuits.Circuit` type. For Unitary Hack submissions, successful implementation for IonQ Harmony device can close this issue and *receive bounty!* For further guidance and implementation tips, see below.

----------------

Here are some further details that may help!

### AwsDevice supported gates

Example of [getting supported gate set](https://docs.aws.amazon.com/braket/latest/developerguide/braket-constructing-circuit.html?tag=local002-20#braket-gates) for IonQ device:

```python
# import the device module
from braket.aws import AwsDevice

device = AwsDevice("arn:aws:braket:us-east-1::device/qpu/ionq/Harmony")

# get device name
device_name = device.name
# show supportedQuantumOperations (supported gates for a device)
device_operations = device.properties.dict()['action']['braket.ir.openqasm.program']['supportedOperations']
print('Quantum Gates supported by {}:\n {}'.format(device_name, device_operations))
```
```python
Quantum Gates supported by the Harmony device:
 ['x', 'y', 'z', 'rx', 'ry', 'rz', 'h', 'cnot', 's', 'si', 't', 'ti', 'v', 'vi', 'xx', 'yy', 'zz', 'swap', 'i']
```

### qBraid DeviceLikeWrapper runtime

In this issue, we implement a function/method that is called after [`_compat_run_input()`](https://github.com/qBraid/qBraid/blob/5143b038b96e46787c019be30504db86042c4cbe/qbraid/devices/aws/device.py#L234) and before [`AwsDevice.run()`](https://github.com/qBraid/qBraid/blob/5143b038b96e46787c019be30504db86042c4cbe/qbraid/devices/aws/device.py#L237) that checks that the Amazon Braket circuit being submitted is composed only of gates that are supported by the target device. For each wrapped AwsDevice, you can get the supported gate set as shown in the example code above.

### Implementation brainstorm

There are a number of approaches that can be taken. Integration with third-party packages is not off the table, but we also want to keep the number of transpilations between different packages to a minimum, if we can, because each time we do one we have the potential of losing information about the circuit, and converting back always runs the risk of popping up new unsupported gates. That being said, here are some options:

- The transpiler already supports conversions to/from pytket. So integrating with the [pytket-extension(s)](https://cqcl.github.io/pytket-extensions/api/index.html) could be one approach.
- Build a native Amazon Braket function modeled after the [`qiskit.compiler.transpiler`](https://github.com/Qiskit/qiskit-terra/blob/c3b0afaab2a3e1331c6b99903a0fe02e8848ca15/qiskit/compiler/transpiler.py#L57) function. Amazon Braket only has ~38 different gates total, and because you know the supported gate sets of each of the devices ahead of time, you may be able to take some shortcuts by solving the most common mappings first, and leverage the qiskit implementation for edge cases.
- A third approach could be to leverage OpenQASM. Amazon Braket circuits can be converted to OpenQASM 3 strings, and that initial, automatic decomposition to the qasm gate set could be a strong first step. From there, you could leverage the qasm standard library to swap operations out programmatically, or simply parse the qasm code line-by-line.

There are many approaches, so pick whichever feels most logical.

**Comment by ryanhill1** [comment]
Related to https://github.com/qiskit-community/qiskit-braket-provider/issues/91

**Comment by rum1887** [comment]
hello @ryanhill1 , interested to take up this issue

**Comment by ryanhill1** [comment]
@rum1887 sounds great!

**Comment by ryanhill1** [comment]
@mmlouamri

**Comment by mmlouamri** [comment]
Thank you! It was a great learning experience 🙏!
