### ISSUE TITLE
Transpiler gate coverage benchmarking

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#234]
We want to get an idea of the qBraid transiler's gate coverage across all of it's different supported packages. The transpiler uses a hub-and-spokes model, centered around cirq. So, for example, when converting a qiskit circuit to Amazon Braket, what you are really doing is converting qiskit to cirq to Amazon Braket. Therefore, are 8 total round of testing needed (to/from cirq x 4 packages): 

- cirq $\longleftrightarrow$ qiskit
- cirq $\longleftrightarrow$ braket
- cirq $\longleftrightarrow$ pyquil
- cirq $\longleftrightarrow$ pytket

The structure of each round of tests would be as follows:

1. Choose source package and target package
2. Gather full gate set of source package, and for supported each gate, create a circuit that uses just that gate.
3. For each circuit in source package set, transpile circuit to target package
4. Check unitary equivalence of the two circuits. If they are equal, test passed. If not, or if an exception was raised, test failed.
5. Final score is # tests passed / total unique gates tested

For Amazon Braket, for example, I could get the full gate set as follows:

```python
import string
from braket.circuits import Gate
# print all available gates in Amazon Braket
gate_set = [attr for attr in dir(Gate) if attr[0] in string.ascii_uppercase]
print(gate_set)
```

There are also `_gate_archive.py` files in the transpiler testing sub-folders for [cirq](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/cirq_qasm/tests/_gate_archive.py), [braket](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/cirq_braket/tests/_gate_archive.py), and [qiskit](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/cirq_qiskit/tests/_gate_archive.py) which hold incomplete gate sets for a few those packages. Some examples of this type of gate-by-gate circuit conversion testing can be found in [`test_transpiler.py`](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/tests/test_transpiler.py). There, you will also find a number of examples of helper functions that can be used to check the unitary equivalence of circuits, for example:

```python
from qbraid.interface import circuits_allclose

circuit_1 = qiskit.QuantumCircuit(...)
circuit_2 = cirq.Circuit(...)
 
assert circuits_allclose(circuit_1, circuit_2, strict_gphase=False)
```

Setting `strict_gphase=False` checks equivalence up-to a global phase, which, for these tests, is all that is required. These benchmarking test-cases should be as new files to the to the `qbraid/transpiler/tests` directory, and in the associated PR contain a brief summary of results.

Most likely, this issue will be broken into sub-issues for each package.

**Comment by JessicaJohnBritto** [comment]
@ryanhill1 Can I work on the cirq to qiskit (and vice-versa)?

**Comment by TheGupta2012** [comment]
@ryanhill1 I'd also like to work on the others, if Jessica's working on the first 2

**Comment by ryanhill1** [comment]
@JessicaJohnBritto On Discord you asked about a good place to get started for cirq to/from qiskit coverage tests. I'll answer here so others can reference as well.

A good starting point for you could be from the [`test_gate_intersect_qiskit_cirq()`](https://github.com/qBraid/qBraid/blob/3cfaba876a224a0722616b3f37b24afa292877cd/qbraid/transpiler/tests/test_transpiler.py#L319) test function. It imports gate dictionaries from the [cirq gate_archive](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/cirq_qasm/tests/_gate_archive.py) and [qiskit gate_archive](https://github.com/qBraid/qBraid/blob/main/qbraid/transpiler/cirq_qiskit/tests/_gate_archive.py), and uses the [`cirq_gate_test_circuit()`](https://github.com/qBraid/qBraid/blob/3cfaba876a224a0722616b3f37b24afa292877cd/qbraid/transpiler/tests/test_transpiler.py#L259) and [`qiskit_gate_test_circuit()`](https://github.com/qBraid/qBraid/blob/3cfaba876a224a0722616b3f37b24afa292877cd/qbraid/transpiler/tests/test_transpiler.py#L244) helper functions to construct a cirq/qiskit circuit using just one gate at a time. And then attempts to make the conversion.

Each of these gate archive files contains an incomplete list. So you will want to add more supported gates for each to determine a good estimate for how many out of the total cirq gates fail to be converted, and same thing for qiskit.

In the above example, we used a sub-set to test just the gates which are explicitly shared between the two. For benchmarking, we don't want to restrict the gate set in this way. Instead, we want to determine exactly which gates are not supported for conversions each way, and have a programmatic way of doing so i.e. a procedure that can be easily updated and re-run in the future. Let me know if that helps!

**Comment by mmlouamri** [comment]
Hey there! It was a great experience working on this issue, and I'm glad that I could contribute to the project. Looking forward to taking on more challenges in the future 🙏 !
