### ISSUE TITLE
Add `circuit_drawer` examples to docs user guide

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#235]
We've recently added a function [`qbraid.interface.circuit_drawer()`](https://github.com/qBraid/qBraid/blob/dbb13874193b5b0619a66e51ec49d878f9d22b15/qbraid/interface/draw.py#L23) that takes any supported program type as input, and draws the quantum circuit representing that program. It interfaces with the circuit drawers of each of the different supported package, allowing for cross-over, also includes a number of different output and format options.

In this issue, we would like to add a section to the [user guide](https://docs.qbraid.com/en/latest/sdk/overview.html) on our docs page showing examples of how this circuit drawer can be used. The code examples should be written in a new `.rst` file [`docs/sdk`](https://github.com/qBraid/qBraid/tree/main/docs/sdk). See [`CONTRIBUTING.md#documentation`](https://github.com/qBraid/qBraid/blob/main/CONTRIBUTING.md#documentation) for instructions on how to build docs locally.

**Comment by nitin-pandita** [comment]
I would like to work on it

**Comment by ryanhill1** [comment]
@nitin-pandita Are you still working on this one as well? Or should I re-assign it?

**Comment by nitin-pandita** [comment]
> @nitin-pandita Are you still working on this one as well? Or should I re-assign it?

@ryanhill1 I am working on it

**Comment by nitin-pandita** [comment]
> 

@ryanhill1 sorry for the delay, I will not make it to the end of this week, you can re-assign it to someone else, sorry for the time delay

**Comment by ryanhill1** [comment]
@nitin-pandita no problem, do you think by end of next week you could get around to it? Or are you occupied with other things at the moment?
