### ISSUE TITLE
OpenQASM 3.0 random circuit function

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#241]
Implement function that generates a "random" circuit written using [OpenQASM 3](https://openqasm.com/versions/3.0/index.html). Should work similar to [Cirq random circuit](https://quantumai.google/reference/python/cirq/testing/random_circuit) and [Qiskit random circuit](https://qiskit.org/documentation/stubs/qiskit.circuit.random.random_circuit.html) functions, but should not explicitly depend on any such third party packages.

**Comment by anomius** [comment]
hi @ryanhill1, i am interested in taking up this issue!

**Comment by ryanhill1** [comment]
@anomius Awesome, it's all yours! Let me know if you have any questions :)
