### ISSUE TITLE
Testing with Mock IBM Provider/Backend

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#251]
Instead of testing against actual IBMQ devices, we want switch relevant tests to construct Mock `IBMProvider` / `IBMBackend` classes so that contributors don't need IBMQ credentials to run unit tests.

Creating mock IBM providers / backends for testing can be modeled after the following examples:
- https://github.com/Qiskit/qiskit-ibm-provider/blob/main/test/unit/mock/fake_account_client.py
- https://github.com/Qiskit/qiskit-ibm-provider/blob/main/test/unit/mock/fake_provider.py

Mock provider / backend updates will effect the following qBraid test modules:
- https://github.com/qBraid/qBraid/tree/main/qbraid/devices/tests
- https://github.com/qBraid/qBraid/tree/main/qbraid/tests

**Comment by TheGupta2012** [comment]
Hi @ryanhill1, was working on this issue.
