### ISSUE TITLE
OpenQASM circuit drawer cont. - fix qubit indexing `ValueError`

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#269]
Following up on https://github.com/qBraid/qBraid/issues/227 with additional improvements needed from PR https://github.com/qBraid/qBraid/pull/247:

In our [`draw_circuit()`](https://github.com/qBraid/qBraid/blob/7bb7c8b7436741a0c26c3f5d61a4af9ccaa16a5a/qbraid/interface/qbraid_qasm/circuit_drawer.py#L330) function, we get a `ValueError` for circuit OpenQASM 3 inputs depending on the qubit indexing / gate array shape broadcasting. See example below:

```python3
from qiskit.qasm3 import loads
from qbraid.interface.qbraid_qasm.circuit_drawer import draw_circuit

qasm3_str = """
OPENQASM 3;
include "stdgates.inc";
qubit[3] _all_qubits;
let q = _all_qubits[0:2];
swap q[0], q[2];
"""

qiskit_circuit = loads(qasm3_str)

print(qiskit_circuit.draw())
print()
print(draw_circuit(qasm3_str))
```
```python3
esc__all_qubits_0: ─X─
                    │ 
esc__all_qubits_1: ─┼─
                    │ 
esc__all_qubits_2: ─X─

Traceback (most recent call last):
  File "/Users/rh1/qBraid/qbraid/interface/qbraid_qasm/tests/openqasm_draw.py", line 56, in <module>
    print(draw_circuit(error_str))
  File "/Users/rh1/qBraid/qbraid/interface/qbraid_qasm/circuit_drawer.py", line 341, in draw_circuit
    circuit, pos = add_gate(circuit, g)
  File "/Users/rh1/qBraid/qbraid/interface/qbraid_qasm/circuit_drawer.py", line 266, in add_gate
    circuit[reg_idxes, pos : pos + g.get_width()] = g.mat()
  File "/Users/rh1/qBraid/qbraid/interface/qbraid_qasm/circuit_drawer.py", line 228, in mat
    mat[2 : 3 * height - 2, :] = [" ", "|", " "] * ((3 * height - 3) - 2)
ValueError: could not broadcast input array from shape (12,) into shape (5,3)
```

_Originally posted by @ryanhill1 in https://github.com/qBraid/qBraid/pull/247#pullrequestreview-1477579685_

**Comment by CalebMcIrvinGitHub** [comment]
The problem here is with the `_all_qubits` syntax. I believe something like `qubit[3] q;` would work, but I'll make the adjustments to allow for both types of syntax.

**Comment by CalebMcIrvinGitHub** [comment]
@ryanhill1 Created a PR to fix this bug. My earlier comment was actually not the cause of the issue; I'd forgotten that my logic already included support for both types of syntax.
