### ISSUE TITLE
The QBraid Environment is not working  

### ISSUE THREAD

**Issue by AbdullahKazi500** [qBraid/qBraid#282]
### Environment

The QBraid Environment is not working  

### What happened?

I was trying to work on QBraid and it is giving me errors

### What is the expected outcome?

NA

**Comment by ryanhill1** [comment]
Hi there! Could you give a little more info about the errors you're getting?

**Comment by AbdullahKazi500** [comment]
Hi @ryanhill1 I was working on QBraid and the problem got fixed thanks
