### ISSUE TITLE
Convert quantum circuits to tensors

### ISSUE THREAD

**Issue by rryoung98** [qBraid/qBraid#293]
### What should we have?

tensorflow_quantum has `tfq.covert_to_tensor` and `tfq.from_tensor` to convert circuits into tensors for machine learning etc. 

Since tfq is pretty fickle and doesn't have a distribution for M1 Chips, it would be a nice to have on qBraid SDK

**Comment by ryanhill1** [comment]
Possibly could be more applicable in https://github.com/qBraid/qbraid-algorithms, unless it's purely a transpiler integration
