### ISSUE TITLE
OpenQASM 3 circuit depth function

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#295]
Write function that takes in OpenQASM 3 string as argument and returns the int circuit depth.

Similar to [`qasm_depth()`](https://github.com/qBraid/qBraid/blob/87bd183e8f1262df7a6ea939c74c81b74d1ea050/qbraid/interface/qbraid_qasm/tools.py#L48) but for qasm3 instead of qasm2, and which does not use any external libraries.

**Comment by TheGupta2012** [comment]
@ryanhill1 , I found that the `qasm_depth` gives the following error when executed as follows - 

```python3
In [6]: from qbraid.interface.qbraid_qasm.tools import qasm_depth

In [7]: test_str_2 = """
   ...: OPENQASM 2.0;
   ...: include "qelib1.inc";
   ...: qreg q[2];
   ...: qreg q2[4];
   ...: creg c[2]; 
   ...: cx q[0], q[1];
   ...: cx q[0], q2[2];
   ...: h q[1];
   ...: z q[0];
   ...: """

In [8]: qasm_depth(test_str_2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 qasm_depth(test_str_2)

File ~/Desktop/college/quantum/Unitary Fund/Unitary-Hack/qBraid/qbraid/interface/qbraid_qasm/tools.py:73, in qasm_depth(qasmstr)
     70 matches = set(map(int, re.findall(r"q\[(\d+)\]", s)))
     72 # Calculate max depth among the qubits in the current line.
---> 73 max_depth = max(counts_dict[f"q[{i}]"] for i in matches)
     75 # Update depths for all qubits in the current line.
     76 for i in matches:

ValueError: max() arg is an empty sequence
```

I feel some of the assumptions used in `qasm_depth` aren't correct - 
1. Parsing line by line and looking for qubit arguments with register name as `q` isn't the right approach. A register may have a name other than `q` too. 
2. Incrementing the count pertaining to a qubit, whenever it is encountered as an argument may be incorrect. This is because of custom gate definitions.

**Comment by ryanhill1** [comment]
@TheGupta2012 Thank's for pointing this out!

1. I agree that parsing for `q` is not the right approach. This accounts for most cases, but like you mentioned, the qubits can be named anything, not necessarily `q`. So we'll want to adapt the function to get the qubit names and use that in the search.

2. I think that incrementing the count pertaining to a qubit is the best approach. In the function, before entering the loop to start counting, we exclude any lines that define custom gate definitions (i.e. lines that start with "gate") so that we don't miscount:

https://github.com/qBraid/qBraid/blob/a572428d2e307fdb0286098e627f4e148c15f17c/qbraid/interface/qbraid_qasm/tools.py#L82

But there may be other edge cases where qubit names are mentioned that are not currently excluded. So we can definitely look into that more as well.

**Comment by ryanhill1** [comment]
@TheGupta2012 I've updated the [`qasm_depth()`](https://github.com/qBraid/qBraid/blob/7b01267ef3a3c7c8ac47ef803ebdcdeb8692d355/qbraid/interface/qbraid_qasm/tools.py#L46) function to account for all edge cases I could find in https://arxiv.org/abs/1707.03429, see [test cases](https://github.com/qBraid/qBraid/blob/7b01267ef3a3c7c8ac47ef803ebdcdeb8692d355/qbraid/interface/qbraid_qasm/tests/test_qasm_utils.py#L181). The implementation can definitely be improved, but seems to be working. Regardless, the updated `qasm_depth` function should at least now provide a decent outline for re-implementing [`qasm3_depth()`](https://github.com/qBraid/qBraid/blob/7b01267ef3a3c7c8ac47ef803ebdcdeb8692d355/qbraid/interface/qbraid_qasm3/tools.py#L61) without qiskit dependency. If you're still interested, I'll leave that one to you!

**Comment by TheGupta2012** [comment]
Thanks @ryanhill1 for the updates! I was working on the contiguous qasm issue and will pick this up now.
