### ISSUE TITLE
OpenQASM 3 convert to contiguous

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#298]
Write function that converts an QASM 3 string circuit to use only contiguous qubit indexing i.e removes empty registers of unused qubits. Similar to [`_convert_to_contiguous_qasm()`](https://github.com/qBraid/qBraid/blob/87bd183e8f1262df7a6ea939c74c81b74d1ea050/qbraid/interface/qbraid_qasm/tools.py#L54C5-L54C32) but for qasm3 instead of qasm2, and implemented without any external dependencies, i.e. should not rely on cirq conversion as existing qasm2 implementation does.

**Comment by TheGupta2012** [comment]
Can I take a look at this too @ryanhill1 ?

**Comment by ryanhill1** [comment]
@TheGupta2012 absolutely!
