### ISSUE TITLE
Refactor to separate core and optional dependencies

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#355]
Follow-up to https://github.com/qBraid/qBraid/issues/175

As the SDK continues to add more frameworks, it is becoming too large. To make the SDK more light weight we should separate out core dependencies. E.g. if someone wants to use the SDK just to transpile circuits between two packages, they shouldn't have to install all of the other packages that they will never use.

As of [v0.4.4](https://github.com/qBraid/qBraid/releases/tag/v0.4.4) the core dependencies would be

```
cirq
numpy
requests
```

and the optional dependencies would be

```
amazon-braket-sdk
pyquil
pytket
pytket-braket
qiskit
qiskit-ibm-provider
qiskit-qasm3-import
```

These optional dependencies could then be grouped into different [`extras`](https://github.com/qBraid/qBraid/blob/a572428d2e307fdb0286098e627f4e148c15f17c/setup.cfg#L45) to allow users to optionally install them based on which framework(s) they need to convert between. 

Implementation while require a top-to-bottom refactoring. Further work is needed to plan out what exactly this new architecture would look like.

Linking further description: https://github.com/qBraid/qBraid/pull/357#pullrequestreview-1590205569

@TheGupta2012 @mmlouamri @rryoung98 @junliangtan1 @poig

**Comment by EnriqueAnguianoVara** [comment]
Hi! Can I work on this?

**Comment by ryanhill1** [comment]
Also related to https://github.com/qBraid/qBraid/issues/186
