### ISSUE TITLE
Core/optional dependency refactor: `qbraid._qprogram`

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#367]
Sub-issue to https://github.com/qBraid/qBraid/issues/355

Update [`qbraid._qprogram.py`](https://github.com/qBraid/qBraid/blob/main/qbraid/_qprogram.py) so that `QPROGRAM_TYPES` and `QPROGRAM_LIBS` are constructed based on the packages that installed. For example, by default, `QPROGRAM_LIBS` should only return libraries available from the core requirements, i.e.:

```python
>>> from qbraid import QPROGRAM_LIBS
>>> QPROGRAM_LIBS
['cirq',  'qasm2']
```
But if I then installed some optional dependencies e.g. https://github.com/qBraid/qBraid/issues/355#issuecomment-1693551837

```bash
$ pip install 'qbraid[qiskit]'
```
then the `QPROGRAM_LIBS` would be updated accordingly:

```python
>>> from qbraid import QPROGRAM_LIBS
>>> QPROGRAM_LIBS
['cirq', 'qiskit', 'qasm2', 'qasm3']
```

**Comment by EnriqueAnguianoVara** [comment]
Hi @ryanhill1 I think [this commit that I've made in my fork repo](https://github.com/EnriqueAnguianoVara/qBraid/commit/2e01299d6baec9d50159f1edd4ccb6772401a460) might resolve this issue.
