### ISSUE TITLE
Allow passing device object directly to `device_wrapper`

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#387]
Allow passing `AwsDevice` or `IBMBackend` directly to `qbraid.device_wrapper` as an alternative to qBraid device ID or vendor device ID.

**Comment by EnriqueAnguianoVara** [comment]
I think I can do this. If it is possible, can you assign me?

**Comment by EnriqueAnguianoVara** [comment]
@ryanhill1 Hi! I have a question. What classes are going to be the output parameters with this modification?

**Comment by ryanhill1** [comment]
@EnriqueAnguianoVara The output will be a [`qbraid.providers.DeviceLikeWrapper`](https://github.com/qBraid/qBraid/blob/f4cb44c1f262092a9bb6ebadd639d8702904f423/qbraid/providers/device.py#L35) object, same as currently specified in [docstring](https://github.com/qBraid/qBraid/blob/f4cb44c1f262092a9bb6ebadd639d8702904f423/qbraid/wrappers.py#L86).
