### ISSUE TITLE
Qiskit <--> Braket direct conversion via OpenQASM 3

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#388]
Currently, transpiling circuits between Qiskit and Amazon Braket requires going through Cirq as an intermediate conversion. Now that Amazon Braket supports converting circuits to/from OpenQASM 3, we can setup a direct link for conversions between qiskit and braket. Will eventually integrate with https://github.com/qBraid/qBraid/issues/359

**Qiskit $\leftrightarrow$ Amazon Braket**

*Current*:

qiskit $\leftrightarrow$ qasm2 $\leftrightarrow$ cirq $\leftrightarrow$ braket

*Desired*:

qiskit $\leftrightarrow$ qasm3 $\leftrightarrow$ braket

**Comment by TheGupta2012** [comment]
Hi @ryanhill1 , I see that [qiskit-braket-provider](https://github.com/qiskit-community/qiskit-braket-provider/tree/main) package has already achieved this conversion. Specifically [convert_qiskit_to_braket_circuit](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/qiskit_braket_provider/providers/adapter.py#L411) does exactly what is required here, just directly and not through `openqasm3`. I think #359 can also benefit from this.

We can leverage/take inspiration from that to make our own converters. Let me know what you think about this.
