### ISSUE TITLE
Add support for `openqasm3.ast.Program` type

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#403]
At the top level, it would also make sense to add support for passing `openqasm3.ast.Program` to through circuit wrapper and having compatibility with the transpiler, e.g.

```python
>>> from qbraid import circuit_wrapper
>>> from openqasm3 import parse
>>> qasm_str = """
... OPENQASM 3.0;
... qubit[4] q;
... h q[0];
... cnot q[0], q[1];
... """
>>> qasm_program = parse(qasm_str)
>>> type(qasm_program)
<class 'openqasm3.ast.Program'>
>>> qbraid_program = circuit_wrapper(qasm_program)
...
```

This new integration would simply extend the existing functions implemented in OpenQASM 2 & 3 modules by extracting the underlying qasm string before making a conversion, e.g. the circuit wrapper would just perform `openqasm3.dumps(qasm_program)` to convert to qasm2 or qasm3 string, and then perform the conversion as usual.

--- 

As a second part to this issue, I'm thinking that the OpenQASM 2 & 3 wrapper classes and interface modules could potentially be streamlined if we use the `openqasm3` package to process input/output qasm string program types. There might be some elegant way to leverage the built-in features of the `openqasm3` package to reduce redundancy/simplify some of the existing functions e.g. [`openqasm3.parser`](https://github.com/openqasm/openqasm/blob/ddd7a70ea99ab59728021bcbc40f681c2a8e0133/source/openqasm/openqasm3/parser.py) to simplify [`draw_circuit()`](https://github.com/qBraid/qBraid/blob/5c708c7d3e7e5f14183d11ec0767d8f5d17e8043/qbraid/interface/qbraid_qasm3/circuit_drawer.py#L402), [`convert_to_qasm3`](https://github.com/qBraid/qBraid/blob/5c708c7d3e7e5f14183d11ec0767d8f5d17e8043/qbraid/interface/qbraid_qasm3/tools.py#L329),  and/or [`openqasm3.printer`](https://github.com/openqasm/openqasm/blob/ddd7a70ea99ab59728021bcbc40f681c2a8e0133/source/openqasm/openqasm3/printer.py) to simplify [`_qasm3_random`](https://github.com/qBraid/qBraid/blob/5c708c7d3e7e5f14183d11ec0767d8f5d17e8043/qbraid/interface/qbraid_qasm3/random_circuit.py#L75).

**Comment by ryanhill1** [comment]
@TheGupta2012 By the way, you might've noticed but I removed the explicit `openqasm3.ast.Program` wrapper class because almost all of its methods were redundant with the existing [`OpenQasm3Program`](https://github.com/qBraid/qBraid/blob/79306c1be8e9d9dff7c4cdc4c3247467f58993a7/qbraid/programs/qasm3.py#L26) string wrapper class, and instead just detected the `openqasm3.ast.Program` type in the `circuit_wrapper` function, and dumped it into a string before proceeding: 

https://github.com/qBraid/qBraid/blob/79306c1be8e9d9dff7c4cdc4c3247467f58993a7/qbraid/wrappers.py#L57-#L58

**Comment by TheGupta2012** [comment]
Yea that makes more sense I guess, I was also feeling some redundancy while building that class.
