### ISSUE TITLE
OpenQASM 3 reverse qubit ordering function

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#409]
Implement function `reverse_qubit_order` in

https://github.com/qBraid/qBraid/blob/79306c1be8e9d9dff7c4cdc4c3247467f58993a7/qbraid/programs/qasm3.py#L246

*Optional Bonus:* Extend function not just reverse qubit ordering, but transform circuit to new qubit indexing specified by an input qubit mapping dictionary.

**Comment by TheGupta2012** [comment]
@ryanhill1 can I work on this and also fix second half of #403 ?

**Comment by ryanhill1** [comment]
@TheGupta2012 Yup absolutely!
