### ISSUE TITLE
Include QIR in transpiling capabilities

### ISSUE THREAD

**Issue by rryoung98** [qBraid/qBraid#435]
## Just some quick thoughts from Munich Quantum Software Forum

We'd like to add QIR alongside QASM 2 and 3 for interoperability with other packages, hardware, and for QEC compatibility. Having QIR will help with integrating with [OQC](https://github.com/oqc-community/qat) and I believe there should be some discussion on how qBraid can be as interoperable and building some interoperability with QASM which is more gate based as well as [Qiskit etc](https://github.com/microsoft/qiskit-qir). We already support qiskit, cirq, pytket, qasm 2 and 3 with kak decomposition (though scaling for gate decompositions should be another issue).

Thoughts from @mstechly https://www.mustythoughts.com/beyond-circuits.html

Source: https://devblogs.microsoft.com/qsharp/introducing-quantum-intermediate-representation-qir/

**Comment by ryanhill1** [comment]
Seems like best initial integration would be to use [`qwop`](https://github.com/crazy4pi314/qwop) to convert between Cirq / OpenQASM 2 via [`export_block()`](https://github.com/crazy4pi314/qwop/blob/168eb68c4d550734ed0545380076f54775c74e69/qwop/exporters/interface.py#L88)

**Comment by ryanhill1** [comment]
Boxed layer 1 (language-specific conversion) represents proposed integration with qBraid-SDK transpiler, coinciding with architecture.png

<img width="793" alt="qir-abstraction" src="https://github.com/qBraid/qBraid/assets/46977852/9c928478-57eb-4ece-a1ae-e094d23ba0ed">

**Comment by ryanhill1** [comment]
Implementation underway in separate qbraid-qir package repo. To later be integrated as plugin.

In progress: cirq -> QIR
Future: OpenQASM3 -> QIR

**Comment by ryanhill1** [comment]
Coming soon: https://docs.qbraid.com/projects/qir
