### ISSUE TITLE
Documentation updates for v0.5.0

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#522]
The following documentation updates are needed before we can release qBraid-SDK v0.5.0:

- [ ] [Programs](https://docs.qbraid.com/en/latest/sdk/programs.html): new `QuantumProgram` methods (e.g. `unitary`, `unitary_rev_qubits`, `unitary_little_endian`, `remove_idle_qubits`, `reverse_qubit_order`)
- [ ] [Transpiler](https://docs.qbraid.com/en/latest/sdk/transpiler.html): overview new transpiler architecture including [convert_to_package](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/interface/converter.py#L97) and [conversion_graph.py](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/interface/conversion_graph.py), and using [plot_conversion_graph](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/visualization/plot_conversion_graph.py#L19) as an example.
- [ ] [Providers](https://docs.qbraid.com/en/latest/sdk/providers.html): overview new providers classes and methods. [QbraidProvider](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/provider.py#L44): `get_devices`, `get_device`. [BraketProvider](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/aws/provider.py#L30): `get_tasks_by_tag`. [QiskitProvider](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/ibm/provider.py#L26): `ibm_least_busy_qpu`
- [ ] [Devices](https://docs.qbraid.com/en/latest/sdk/devices.html): new [QuantumDevice](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/device.py#L36) methods: `transpile`, `compile`, `queueDepth`, `run_batch`, submitting "tagged" jobs using tags kwarg in run method. [BraketDevice](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/aws/device.py#L41): `availability_window`
- [ ] [Jobs](https://docs.qbraid.com/en/latest/sdk/jobs.html): [QuantumJob](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/job.py#L31) `wait_for_final_state`, `status_final`. [BraketQuantumTask](https://github.com/qBraid/qBraid/blob/aa86a58e0e55177e407efe86e7d1befc3a5ae4fb/qbraid/providers/aws/job.py#L32): `queuePosition`, `get_cost`
- [ ] Visualization: circuit drawer example, especially with new qasm3 draw. see https://github.com/qBraid/qBraid/issues/235
- [ ] End-to-end use-case examples

**Comment by smburdick** [comment]
@ryanhill1 I'd be happy to take this on for you.

**Comment by smburdick** [comment]
@ryanhill1 No worries, and thanks, I'll start with `Program`s and work my way down the list

**Comment by ryanhill1** [comment]
@smburdick This sounds great, looking forward to reviewing! If you come across bugs or other features that could be improved along the way, please feel free to open issues!
