### ISSUE TITLE
NetworkX Out, Rustworkx In: Unleash the Speed

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#618]
The primary goal of this transition is to enhance the performance of our graph-based [transpiler](https://github.com/qBraid/qBraid/tree/0703289807cef1d8412c2c0cedeceffe8dec27ed?tab=readme-ov-file#transpiler) by replacing our current NetworkX implementation with [Rustworkx](https://github.com/Qiskit/rustworkx) (yay Qiskit!). Benchmarking shows that Rustworkx offers significant performance improvements and better memory management compared to Python-based NetworkX.

The affected files include **but are not limited to** the following: 

- [pyproject.toml](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/pyproject.toml#L27)
- [requirements.txt](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/requirements.txt#L1)
- [README.md](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/README.md)
- [qbraid/_about.py](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/_about.py)
- [tests/top_level/test_about.py](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/tests/top_level/test_about.py)
- [qbraid/transpiler/graph.py](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/transpiler/graph.py)
- [qbraid/visualization/plot_conversions.py](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/visualization/plot_conversions.py)
- [tests/transpiler/test_conversion_graph.py](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/tests/transpiler/test_conversion_grah.py)

**Comment by king-p3nguin** [comment]
Hi, I am working on this issue and would like to be assigned after successfully merging the PR.
