### ISSUE TITLE
 Challenge Accepted: Boost Our Code with Cython!

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#619]
[CPython](https://github.com/python/cpython) is renowned for its optimization capabilities, offering potential for significant performance enhancements. It's time to tap into that potential! We're inviting you to integrate CPython anywhere in our codebase and demonstrate a measurable improvement in performance.

## The Challenge

**Integration**: Use CPython to optimize the time and/or space complexity in any part of the qBraid-SDK codebase. While improvements are welcome across the board, insiders know that the `qbraid.transpiler` module might just be the hidden gem you’re looking for 👀 💎 .

**Demonstration**: Provide statistical evidence of performance enhancements, focusing on execution time or memory usage.

**Documentation**: Include benchmarks, performance comparisons, and your methodology in your pull request.

**Comment by Hope-Alemayehu** [comment]
Hi, I would like to work on this issue. Can I be assigned to it? I have a background in competitive programming and have been working in quantum computing since 2021.

**Comment by ryanhill1** [comment]
@Hope-Alemayehu Absolutely!

**Comment by Hope-Alemayehu** [comment]
What should our priority be: optimizing for time or space? Which trade-off is less costly for Qbraid?

**Comment by ryanhill1** [comment]
@Hope-Alemayehu Both are great but I would say optimizing for time, if I had to choose!

**Comment by ryanhill1** [comment]
@Hope-Alemayehu How are things going? If you're finding the transpiler difficult to optimize, the [qbraid.interface.circuit_equality](https://github.com/qBraid/qBraid/blob/950f37378352ac4f2db87949ce607a3527ce227d/qbraid/interface/circuit_equality.py) module is another greater opportunity for improvement with CPython. Matrix calculations can be extremely costly at large dimensions.

**Comment by Hope-Alemayehu** [comment]
I was working on the transpiler and made some improvements. While I understand how to analyze the time complexity and the nature of the improvements, I found it challenging to provide statistical evidence. Would it be acceptable to present the analysis using Big O notation?

**Comment by ryanhill1** [comment]
@Hope-Alemayehu Yep that works!

**Comment by ryanhill1** [comment]
@shubhamkaushal765 Absolutely, go for it!

**Comment by shubhamkaushal765** [comment]
Hi @ryanhill1, Thanks!

I wanted to ask for a clarification: I believe you mean [Cython](https://cython.org/) instead of CPython, as the former provides the c-extension to Python which gives time/memory improvements.

from [this](https://stackoverflow.com/questions/17130975/python-vs-cpython) discussion:

> So CPython does not translate your Python code to C by itself. Instead, it runs an interpreter loop. There is a project that does translate Python-ish code to C, and that is called [Cython](http://cython.org/). Cython adds a few extensions to the Python language, and lets you compile your code to C extensions, code that plugs into the CPython interpreter.

**Comment by ryanhill1** [comment]
@shubhamkaushal765 Yes, that's what I meant! Thanks for the clarification
