### ISSUE TITLE
Expand IonQ provider runtime to supported gates

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#625]
The qBraid runtime [IonQDevice.extract_gate_data](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/runtime/ionq/device.py#L68) method is used to convert an [openqasm3.ast.Program](https://github.com/openqasm/openqasm/blob/4ca1d793833b24a195dcb8a5db99f1bd21b0d32f/source/openqasm/openqasm3/ast.py#L136) to the [json-based circuit-encoding format](https://docs.ionq.com/api-reference/v0.3/writing-quantum-programs#bell-state) required to [submit jobs via POST request](https://docs.ionq.com/api-reference/v0.3/jobs/create-a-job) using the IonQ API. Currently, this method only represents a minimal working example, so only supports the `h` and `cnot` gates. We would like to expand this method to allow submitting OpenQASM programs written using any of the [IonQ supported gate](https://docs.ionq.com/api-reference/v0.3/writing-quantum-programs#supported-gates):

| Supported | Gate | Description                            |
|------------|------|----------------------------------------|
| | `x`    | Pauli X gate                           |
| | `y`    | Pauli Y gate                           |
| | `z`    | Pauli Z gate                           |
| | `rx`   | X-axis rotation                        |
| | `ry`   | Y-axis rotation                        |
| | `rz`   | Z-axis rotation                        |
| x | `h`    | Hadamard gate                          |
| | `not`  | Convenient alias for Pauli-X gate      |
| x | `cnot` | Convenient alias for controlled-not gate |
|  | `s`    | S gate                                 |
| | `si`   | Conjugate transpose of S gate          |
| | `t`    | T gate                                 |
| | `ti`   | Conjugate transpose of T gate          |
| | `v`    | Square root of not gate                |
| | `vi`   | Conjugate transpose of square-root-of-not gate |
| | `swap` | Swaps two qubits                       |

**Comment by king-p3nguin** [comment]
Hi, I would like to work on this issue for unitaryhack.
