### ISSUE TITLE
Convert OpenQASM 3 program to specified basis gate set

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#626]
## Overview

We need to develop a function that can take any given OpenQASM 3 program and convert it into an equivalent program that exclusively utilizes a pre-defined set of basis gates. This function is crucial for ensuring that our quantum programs are compatible with quantum processors that support limited gate sets.

## Usage example

The example test case below shows how the `convert_to_basis_gates` function, given a basis gate set ["h", "cx"], would decompose the controlled-z gate.

```python
# qbraid.transforms.qasm3.transform.py

from openqasm3.parser import parse

def convert_to_basis_gates(qasm: str, basis_gates: list[str]) -> str:
    """
    Converts an OpenQASM 3 program to an equivalent program that only uses the specified basis gates.

    Args:
        openqasm_program (str): The original OpenQASM 3 program as a string.
        basis_gates (list[str]): A list of gate names allowed in the basis set.

    Returns:
        str: The converted OpenQASM 3 program.

    Raises:
        ValueError: if the decomposition is not possible
    """
    program = parse(qasm)
    
    ... TODO

    return converted_program
```

```python
# tests.transforms.test_qasm3_transforms.py

from qbraid.transforms.qasm3.transform import convert_to_basis_gates

def test_convert_to_basis_gates():
    original_program = """
    OPENQASM 3;
    include "stdgates.inc";
    qubit[2] q;
    cz q[0], q[1];
    """

    basis_gates = ["h", "cx"]

    converted_program = convert_to_basis_gates(original_program, basis_gates)

    expected_program = """
    OPENQASM 3;
    include "stdgates.inc";
    qubit[2] q;
    h q[1];
    cx q[0], q[1];
    h q[1];
    """

    assert converted_program == expected_program
```

## Scope

To help restrict the scope of this issue, your implementation can make the following assumptions:

1. The input OpenQASM 3 program does not include subroutines, custom gate definitions, external functions, or modifiers.
2. The input OpenQASM 3 program consists solely of gates from the standard gate library (i.e., "stdgates.inc", see image below from https://arxiv.org/abs/2104.14722)
3. The input basis gate set consists solely of standard gates from the following group:

```
[x, y, z, rx, ry, rz, h, cx, s, sdg, t, tdg, sx, sxdg, swap]
```

## Requirements

1. Your implementation must leverage the `openqasm3` library to parse and traverse the input program. You should *not* traverse the raw input string. Trust me, this will make your life *so* much easier. For example:

```python
import openqasm3

qasm3_str = "......"

program: openqasm3.ast.Program = openqasm3.parser.parse(qasm3_str)

for statement in program.statements:
    if isinstance(statement, openqasm3.ast.QuantumGate):
        name = statement.name.name
        qubits = statement.qubits
    ...
```

2. Your implementation cannot use any other external dependencies outside of the qBraid-SDK's core [requirements](https://github.com/qBraid/qBraid/blob/main/requirements.txt). However, it can utilize any methods from the [OpenQasm3Program](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/programs/libs/qasm3.py#L27) class and/or any existing functions from [qbraid.transforms.qasm3](https://github.com/qBraid/qBraid/blob/0703289807cef1d8412c2c0cedeceffe8dec27ed/qbraid/transforms/qasm3/compat.py) as applicable.

## Standard gate definitions

```c
// OpenQASM 3 standard gate library

// phase gate
gate p(λ) a { ctrl @ gphase(λ) a; }

// Pauli gate: bit-flip or NOT gate
gate x a { U(π, 0, π) a; }
// Pauli gate: bit and phase flip
gate y a { U(π, π/2, π/2) a; }
// Pauli gate: phase flip
gate z a { p(π) a; }

// Clifford gate: Hadamard
gate h a { U(π/2, 0, π) a; }
// Clifford gate: sqrt(Z) or S gate
gate s a { pow(1/2) @ z a; }
// Clifford gate: inverse of sqrt(Z)
gate sdg a { inv @ pow(1/2) @ z a; }

// sqrt(S) or T gate
gate t a { pow(1/2) @ s a; }
// inverse of sqrt(S)
gate tdg a { inv @ pow(1/2) @ s a; }

// sqrt(NOT) gate
gate sx a { pow(1/2) @ x a; }

// Rotation around X-axis
gate rx(θ) a { U(θ, -π/2, π/2) a; }
// rotation around Y-axis
gate ry(θ) a { U(θ, 0, 0) a; }
// rotation around Z axis
gate rz(λ) a { gphase(-λ/2); U(0, 0, λ) a; }

// controlled-NOT
gate cx c, t { ctrl @ x c, t; }
// controlled-Y
gate cy a, b { ctrl @ y a, b; }
// controlled-Z
gate cz a, b { ctrl @ z a, b; }
// controlled-phase
gate cp(λ) a, b { ctrl @ p(λ) a, b; }
// controlled-rx
gate crx(θ) a, b { ctrl @ rx(θ) a, b; }
// controlled-ry
gate cry(θ) a, b { ctrl @ ry(θ) a, b; }
// controlled-rz
gate crz(θ) a, b { ctrl @ rz(θ) a, b; }
// controlled-H
gate ch a, b { ctrl @ h a, b; }

// swap
gate swap a, b { cx a, b; cx b, a; cx a, b; }

// Toffoli
gate ccx a, b, c { ctrl @ ctrl @ x a, b, c; }
// controlled-swap
gate cswap a, b, c { ctrl @ swap a, b, c; }
// four parameter controlled-U gate with relative phase γ
gate cu(θ, ϕ, λ, γ) c, t { p(γ) c; ctrl @ U(θ, ϕ, λ) c, t; }

// Gates for OpenQASM 2 backwards compatibility
// CNOT
gate CX c, t { ctrl @ U(π, 0, π) c, t; }
// phase gate
gate phase(λ) q { U(0, 0, λ) q; }
// controlled-phase
gate cphase(λ) a, b { ctrl @ phase(λ) a, b; }
// identity or idle gate
gate id a { U(0, 0, 0) a; }
// IBM Quantum experience gates
gate u1(λ) q { U(0, 0, λ) q; }
gate u2(ϕ, λ) q { gphase(-(ϕ+λ)/2); U(π/2, ϕ, λ) q; }
gate u3(θ, ϕ, λ) q { gphase(-(ϕ+λ)/2); U(θ, ϕ, λ) q; }
```

**Comment by anomius** [comment]
I would like to work on this.

**Comment by ryanhill1** [comment]
Hi @anomius. Now that [Unitary Hack](https://unitaryhack.dev/projects/qbraid-sdk/) has officially started, feel free to start on this issue.

For others: Remember that multiple people can work a single issue at once!

> For pull requests resolving bountied issues, the first accepted PR from the project maintainers will receive the prize!

See [rules](https://unitaryhack.dev/rules/).

**Comment by dhanaabhirajk** [comment]
Hi @ryanhill1  I was interested in taking up this issue!

**Comment by ryanhill1** [comment]
@dhanaabhirajk Awesome, go for it!

**Comment by dhanaabhirajk** [comment]
@ryanhill1 When converting to basic gates, whether the formation of gates between the basic gates also should be handled. For example,  y Gate formation, if available basic gates are x and z.

```python

# Example usage:

qasm_program = """
openqasm 3.0;
include "stdgates.inc";

qubit q[0];
y q[0];
"""
```

**Comment by ryanhill1** [comment]
Hi @dhanaabhirajk, thanks for the question! Yes, the formation of gates from within the allowed basis gate set should also be handled.

You can assume the input basis gates set is composed solely of gates from the before-mentioned group:

```
[x, y, z, rx, ry, rz, h, cx, s, sdg, t, tdg, sx, sxdg, swap]
```

However, you *cannot* assume that the input basis gates will represent a complete set of the gates from this group. The basis gate set may contain just ["x", "z"], as in your example, and in that case, any other gates in the circuit that are not "x" or "z" would need to be decomposed accordingly, if possible.

**Comment by dhanaabhirajk** [comment]
Hi @ryanhill1 , thanks for the clarification. Are there any deconstruction mapping between the gates available or any other resources related to it. This would help me solving this issue.

**Comment by Ameya28Bhave** [comment]
Hi @ryanhill1 ,I must have missed it but may I know how is 'sxdg' (Conjugate transpose of square-root-of-not gate) gate being implemented ?, reason to ask this is since 'sxdg' is not in OpenQASM 3 standard gate library (i.e., "stdgates.inc")

**Comment by ryanhill1** [comment]
@Ameya28Bhave Thanks for asking!

$$\sqrt{X}^{\dagger} = \frac{1}{2} \begin{pmatrix}
                1 - i & 1 + i \\
                1 + i & 1 - i
            \end{pmatrix}$$

**Comment by ryanhill1** [comment]
@anomius @dhanaabhirajk @Ameya28Bhave How are things going? Any other questions I can help answer or guidance that would be helpful?

**Comment by ryanhill1** [comment]
@anomius @dhanaabhirajk @Ameya28Bhave 

⚠️  *IMPORTANT UPDATE* ⚠️ 

I've discussed with our team, and we've decided to reduce the scope of this issue for Unitary Hack. So now, you can assume the target basis gate set will always be the same:

```
[x, y, z, rx, ry, rz, h, cx, s, sdg, t, tdg, sx, sxdg, swap]
```

meaning that any input OpenQASM 3 program, we just want to convert to these gates. No re-formations of gates that are already part of this target gate set are necessary.

Let me know if there are any questions! Hopefully this can help make that bounty a little more attainable.

**Comment by dhanaabhirajk** [comment]
@ryanhill1 Why Phase gate (p) is avoided in basic gates?

**Comment by ryanhill1** [comment]
@dhanaabhirajk That part's not up to me, that's a good question for IonQ: https://docs.ionq.com/api-reference/v0.3/writing-quantum-programs#supported-gates

**Comment by dhanaabhirajk** [comment]
@ryanhill1 I have raised a PR https://github.com/qBraid/qBraid/pull/662 with converting the openqasm3 program to basic gates for crx, cry, crz,  Cy, cz. I need to iterat le the same for other gates.
