### ISSUE TITLE
Integrate `QuboSolveParams` into native device run/submit method args

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qBraid#800]
We recently added the [`QuboSolveParams`](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/runtime/schemas/experiment.py#L145) schema which details all of the solve parameters available via when submitting a QUBO problem to the native `nec_vector_annelar` device. Usage would look something like the following: 

```python
from pyqubo import Spin

from qbraid import QbraidProvider
from qbraid.runtime.schemas import QuboSolveParams

s1, s2, s3, s4 = Spin("s1"), Spin("s2"), Spin("s3"), Spin("s4")
H = (4 * s1 + 2 * s2 + 7 * s3 + s4) ** 2
model = H.compile()

provider = QbraidProvider()
device = provider.get_device("nec_vector_annealer")

params = QuboSolveParams(
    offset=0.5,
    num_reads=10,
    num_results=5,
    num_sweeps=1000,
    beta_range=(5.0, 100.0, 200),
    beta_list=[1.2, 5.5, 10.0],
)

job = device.run(model, params=params)
```

Small caveat: `device.run` will call

https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/runtime/native/device.py#L305

(where `program` is an instance of `pyqubo.Model`), which will call

https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/runtime/device.py#L288

where the [`TargetSpec.to_ir()`](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/spec.py#L78) method is defined as

https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/runtime/native/provider.py#L53-L55

which will call

https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/_model.py#L113-L115

which will return a JSON where one of the keys is "offset" with value extracted directly from

https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/cpp_pyqubo.py#L36

So this means that once we reach the [`QbraidDevice.submit()`](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/runtime/native/device.py#L77) method, there will be duplicate values specified for "offset". One within the `run_input["problem"]` dictionary, and another provided as an attribute of `QuboSolveParams`.

Resolving this conflict is fairly straight forward from a programing perspective, but it does bring into question whether we want to treat the "offset" value as an intrinsic part of our QUBO problem abstraction, or whether we want to treat offset as a "solve parameter".

If we want to treat it as an intrinsic part of our QUBO problem abstraction, like it currently is, then we can solve this conflict by simply removing the `offset` attribute from the `QuboSolveParams` schema.

However, if we think it is more "accurate" or "consistent" to define our [`qbraid.programs.annealing.Problem`](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/_model.py#L42) abstraction simply in terms of the problem type and the linear and quadratic coefficients (e.g. like in [amazon-braket-schemas](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/src/braket/ir/annealing/problem_v1.py)) then we will need to do a little bit of refactoring around the [AnnealingProgram](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/_model.py#L97), [ProblemEncoder](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/_model.py#L123), and [PyQuboModel](https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/annealing/cpp_pyqubo.py#L24).

Proposed new runtime:

```python
from pyqubo import Spin

from qbraid import QbraidProvider
from qbraid.runtime.schemas import QuboSolveParams
from qbraid.programs.annealing import Problem, ProblemType

s1, s2, s3, s4 = Spin("s1"), Spin("s2"), Spin("s3"), Spin("s4")
H = (4 * s1 + 2 * s2 + 7 * s3 + s4) ** 2
model = H.compile()
qubo, offset = model.to_qubo()

provider = QbraidProvider()
device = provider.get_device("nec_vector_annealer")

params = QuboSolveParams(
    offset=offset,
    num_reads=10,
    num_results=5,
    num_sweeps=1000,
    beta_range=(5.0, 100.0, 200),
    beta_list=[1.2, 5.5, 10.0],
)

problem = Problem(problem_type=ProblemType.QUBO, quadratic=qubo)

job = device.run(problem, params=params)
```

For this to work, we need to register `qbraid.programs.annealing.Program` as a "native" program type similar to how we do for `IonQDict`, see

- https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/_import.py#L123
- https://github.com/qBraid/qBraid/blob/778005f477b94573489d4cf08906dbaf1528a921/qbraid/programs/circuits/ionq.py#L28

So we you will need to create another file e.g. `qbraid.programs.annealing.program.py` that contains a new sub-class of `qbraid.programs.annealing.AnnealingProgram` that takes a `qbraid.programs.annealing.Problem` as argument. The implementation of the one abstract class `to_problem()` will just return the input `Problem`.

**Comment by rryoung98** [comment]
👍

**Comment by rryoung98** [comment]
also as i was testing, another thing i came to realize is that our response handling may need to improve and ill try to work on that as well.

**Comment by rryoung98** [comment]
hey @ryanhill1 given that crs4 hackathon is over, im able to come back to this. Just an fyi, this refactor is not just more "accurate" or "consistent" but necessary as we discovered during the hackathon. The `pyqubo.to_qubo()` [method ](https://pyqubo.readthedocs.io/en/latest/reference/model.html#pyqubo.to_qubo) requires passing in arguments such as `feed_dict` which the original architecture does not make it easy to do. 

Anyways, would it be most appropriate to make an addition to the qbraid.programs.typer file? If so, do we need to keep cpp_pyqubo and other pass implementations?  I think if we are going to refactor to this new architecture, it appears to me that we could also simply repurpose the `PyQuboModel` and go from there.

Let me know if what im saying is confusing! 🦜 

Best,

Ricky

**Comment by ryanhill1** [comment]
Works for me!
